version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
